# Generated by Django 6.0.2 on 2026-04-19 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_assignment_late_penalty_percent_and_more'),
        ('classrooms', '0012_remove_classroom_teacher_join_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('qna', 'Q&A')], default='quiz', max_length=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('qna', 'Q&A')], default='mcq', max_length=10),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='text_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='text_response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.choice'),
        ),
        migrations.CreateModel(
            name='DeadlineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_events', to='classrooms.classroom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_deadline_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'created_at'],
            },
        ),
    ]
