# Generated by Django 5.1.7 on 2026-04-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_assignment_assignment_type_assignment_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='awarded_marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='teacher_feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
