# Generated by Django 6.0.2 on 2026-04-19 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from datetime import timedelta
from django.utils import timezone


def populate_classroom_access_codes(apps, schema_editor):
    Classroom = apps.get_model('classrooms', 'Classroom')

    existing_codes = set()
    for classroom in Classroom.objects.all().order_by('id'):
        if classroom.teacher_join_code:
            existing_codes.add(classroom.teacher_join_code)
        if classroom.join_key:
            existing_codes.add(classroom.join_key)

    for classroom in Classroom.objects.all().order_by('id'):
        if not classroom.created_by_id and classroom.teacher_id:
            classroom.created_by_id = classroom.teacher_id

        if not classroom.teacher_join_code:
            candidate = f"T{classroom.id:09d}"
            existing_codes.add(candidate)
            classroom.teacher_join_code = candidate

        if not classroom.teacher_join_code_expires_at:
            classroom.teacher_join_code_expires_at = timezone.now() + timedelta(days=30)

        classroom.save(update_fields=['created_by', 'teacher_join_code', 'teacher_join_code_expires_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0009_populate_classroom_teachers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classrooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher_join_code',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher_join_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(populate_classroom_access_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='classroom',
            name='teacher_join_code',
            field=models.CharField(default='', editable=False, max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='ClassroomLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='classrooms.classroom')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'unique_together': {('classroom', 'requester', 'role', 'status')},
            },
        ),
    ]
