# Generated by Django 6.0.2 on 2026-04-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0011_classroomteacherjoinrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='teacher_join_code',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='teacher_join_code_expires_at',
        ),
    ]
