# Generated by Django 5.1.7 on 2026-04-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_supportticketmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roll_no',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
